<template>
  <div>
    <bscroll :left="left" :right="right"></bscroll>
  </div>
</template>

<script>
import bscroll from "../components/category/BScroll.vue";
export default {
  data() {
    return {
      left: [
        "精选推荐",
        "女装",
        "男装",
        "男女内衣",
        "女鞋",
        "男鞋",
        "手表配饰",
        "护肤彩妆",
        "箱包皮包",
        "户外活动"
      ],
      right: [
        {
            name:'精选推荐',
          content: [
            {
              id:'cate1',
              img: require("../assets/images/jt1.webp"),
              name: "儿童外套"
            },
            {
                id:'nvy6',
                img:require("../assets/images/female_list6.webp"),
                name:'|polo衫女'
            },
            {
              id:'cate2',
              img: require("../assets/images/jt2.png"),
              name: "眼霜"
            },
            {
              id:'cate3',
              img: require("../assets/images/jt3.png"),
              name: "男士TT恤"
            },
            {
              id:'cate4',
              img: require("../assets/images/fnv2.webp"),
              name: "女式牛仔裤"
            },
            {
              id:'cate5',
              img: require("../assets/images/jt4.webp"),
              name: "儿童T恤"
            },
            {
              id:'cate6',
              img: require("../assets/images/jt5.webp"),
              name: "连衣裙"
            },
            {
              id:'cate7',
              img: require("../assets/images/jt7.png"),
              name: "口红"
            },
            {
              id:'cate8',
              img: require("../assets/images/jt8.webp"),
              name: "休闲女裤"
            },
            {
              id:'beauty3',
              img:require('../assets/images/beauty3.webp'),
              name:'Lancome|兰蔻'
            },
            {
              id:'beauty4',
                img:require('../assets/images/beauty4webp.webp'),
                name:'欧莱雅'
            },
            {
              id:'nvy2',
                img:require("../assets/images/female_list2.webp"),
                 name:"女防晒外套"
            },
            {
              id:'nvy4',
                img:require("../assets/images/female_list4.webp"),
              name:"打底裤"
            },
            {
                id:'nvy5',
                img:require("../assets/images/female_list5.webp"),
                name:'德玛纳背心',
            }
          ]
        },
        {
            name:'女装',
          content: [
            {
                id:'cate9',
              img: require("../assets/images/nz1.jpg"),
              name: "休闲裤"
            },
            {
                id:'cate10',
                img:require("../assets/images/nz2.jpg"),
                name:'连衣裙'
            },
            {
                id:'cate11',
                img:require("../assets/images/nz3.jpg"),
                name:'半身裙'
            },
            {
                id:'cate12',
                img:require("../assets/images/nz4.jpg"),
                name:'衬衫'
            },
            {
                id:'cate13',
                img:require("../assets/images/nz5.jpg"),
                name:'套裙'
            },
            {
                id:'cate14',
                img:require("../assets/images/nz6.jpg"),
                name:'牛仔裤'
            },
            {
                id:'cate15',
                img:require("../assets/images/nz7.png"),
                name:'外套'
            },
            {
              id:'cate16',
              img: require("../assets/images/fnv1webp.webp"),
              name: "女士T恤"
            },
            {
                id:'cate17',
                img:require("../assets/images/nz8.jpg"),
                name:'风衣'
            },
            {
                id:'cate18',
                img:require("../assets/images/nz9.jpg"),
                name:'针织外套'
            },
            {
                id:'cate19',
                img:require("../assets/images/nz10.jpg"),
                name:'妈妈装'
            },
            {
                id:'cate20',
                img:require("../assets/images/nz11png.png"),
                name:'打底裤'
            },
            {
                id:'cate21',
                img:require("../assets/images/nz12.png"),
                name:'羊绒/羊毛衫'
            },
            {
                id:'cate22',
                img:require("../assets/images/nz13.png"),
                name:'阔腿库'
            },
            {
                id:'cate23',
                img:require("../assets/images/nz14.jpg"),
                name:'短裤'
            },
            {
                id:'cate24',
              img: require("../assets/images/fnv2.webp"),
              name: "女式牛仔裤"
            }
          ]
        },
        {
          name: "男装",
          content: [
            {
              id:'cate24',
              img: require("../assets/images/nan1.png"),
              name: "短袖T恤"
            },
            {
              id:'cate24',
              img: require("../assets/images/nan2.png"),
              name: "衬衫"
            },
            {
                id:'cate24',
                img:require("../assets/images/nan3.png"),
                name:"Polo衫"
            },
            {
                id:'cate24',
                img:require("../assets/images/nan4.png"),
                name:'卫衣'
            },
            {
                id:'cate24',
                img:require("../assets/images/nan5.png"),
                name:'夹克'
            },
            {
                id:'cate24',
                img:require("../assets/images/nan6.png"),
                name:'男士套装'
            },
            {
                id:'cate24',
                img:require("../assets/images/nan7.png"),
                name:'休闲库'
            },
            {
                id:'cate24',
                img:require("../assets/images/nan8.png"),
                name:'牛仔裤'
            },
            {
                id:'cate24',
                img:require("../assets/images/nan9.png"),
                name:'Polo衫'
            },
            {
                id:'cate24',
                img:require("../assets/images/nan10.png"),
                name:'长袖衬衫'
            },
            {
                id:'cate24',
                img:require("../assets/images/nan11.png"),
                name:'毛衣'
            },
            {
                id:'cate9',
                img:require("../assets/images/nan12.png"),
                name:'针织衫'
            },
            {
                id:'cate24',
                img:require("../assets/images/nan13.png"),
                name:'短裤'
            },
            {
                id:'cate9',
                img:require("../assets/images/nan14.png"),
                name:'夹克'
            },
            {
                id:'cate9',
                img:require("../assets/images/nan15.png"),
                name:'西装'
            },
            {
                id:'cate9',
                img:require("../assets/images/nan16.png"),
                name:'马甲/背心'
            }
          ]
        },
        {
            name:'男女内衣',
          content: [
            {
                id:'cate9',
              img: require("../assets/images/nei1.png"),
              name: "热卖文胸"
            },
            {
                id:'cate9',
              img: require("../assets/images/nei2.png"),
              name: "男士睡衣"
            },
            {
                id:'cate9',
              img: require("../assets/images/nei3.png"),
              name: "女士睡衣"
            },
            {
                id:'cate9',
                img:require("../assets/images/nei4.png"),
                name:'女士内裤'
            },
            {
                id:'cate9',
                img:require("../assets/images/nei5.png"),
                name:'男士内裤'
            },
            {
                id:'cate9',
                img:require("../assets/images/nei6.png"),
                name:'文胸套装'
            },
            {
                id:'cate9',
                img:require("../assets/images/nei7.png"),
                name:'睡裙睡袍'
            },
            {
                id:'cate9',
                img:require("../assets/images/nei8.png"),
                name:'无钢圈文胸'
            },
            {
                id:'cate9',
                img:require("../assets/images/nei9.png"),
                name:'薄杯文胸'
            },
            {
                id:'inner1',
                img:require("../assets/images/innerwear_list1.webp"),
                name:'美斯',
                newPrice:'59'
            },
            {
                id:'inner2',
                img:require("../assets/images/innerwear_list2.webp"),
                name:'爱慕',
                newPrice:'99'
            },
            {
                id:'inner3',
                img:require("../assets/images/innerwear_list3.webp"),
                name:'美婷',
                newPrice:'89'
            },
            {
                id:'inner4',
                img:require("../assets/images/innerwear_list4.webp"),
                name:'七匹狼',
                newPrice:'59'
            },
            {
                id:'inner5',
                img:require("../assets/images/innerwear_list5.webp"),
                name:'金利来',
                newPrice:'59'
            },
            {
                id:'inner6',
                img:require("../assets/images/innerwear_list6.webp"),
                name:'伊丝艾拉',
                newPrice:'79'
            },
            {
                id:'inner7',
                img:require("../assets/images/innerwear_list7.webp"),
                name:'美思',
                newPrice:'59'
            },
            {
                id:'inner8',
                img:require("../assets/images/innerwear_list8.webp"),
                name:'猫人',
                newPrice:'55'
            },
            {
                id:'inner9',
                img:require("../assets/images/innerwear_list9.webp"),
                name:'木林森',
                newPrice:'59'
            },
            {
                id:'inner10',
                img:require("../assets/images/innerwear_list10.webp"),
                name:'猫人',
                newPrice:'69'
            },
            {
                id:'inner11',
                img:require("../assets/images/innerwear_list11.webp"),
                name:'美思',
                newPrice:'59'
            },
            {
                id:'inner12',
                img:require("../assets/images/innerwear_list12.webp"),
                name:'多拉美',
                newPrice:'59'
            }
          ]
        },
        {
            name:'女鞋',
          content: [
            {
                id:'cate9',
              img: require("../assets/images/nvx1.png"),
              name: "凉鞋"
            },
            {
                id:'cate9',
              img: require("../assets/images/nvx2.png"),
              name: "单鞋"
            },
            {
                id:'cate9',
                img:require("../assets/images/nvx3.jpg"),
                name:'休闲鞋'
            },
            {
                id:'cate9',
                img:require("../assets/images/nvx4.jpg"),
                name:'小白鞋'
            },
            {
                id:'cate9',
                img:require("../assets/images/nvx5.jpg"),
                name:'运动鞋'
            },
            {
                id:'cate9',
                img:require("../assets/images/nvx6.jpg"),
                name:'高跟鞋'
            },
            {
                id:'cate9',
                img:require("../assets/images/nvx7.jpg"),
                name:'老爹鞋'
            },
            {
                id:'cate9',
                img:require("../assets/images/nvx8.png"),
                name:'乐福鞋'
            },
            {
                id:'cate9',
                img:require("../assets/images/nvx9.png"),
                name:'帆布鞋'
            },
            {
                id:'cate9',
                img:require("../assets/images/nvx3.jpg"),
                name:'休闲鞋'
            },
            {
                id:'cate9',
                img:require("../assets/images/nvx4.jpg"),
                name:'小白鞋'
            },
            {
                id:'cate9',
                img:require("../assets/images/nvx5.jpg"),
                name:'运动鞋'
            },
          ]
        },
        {
            name:'男鞋',
          content: [
            {
              id:'kong4',
              img: require("../assets/images/nanx1.png"),
              name: "休闲鞋"
            },
            {
               id:'kong4',
              img: require("../assets/images/nanx2.jpg"),
              name: "凉鞋"
            },
            {
                id:'kong4',
                img:require("../assets/images/nanx3.jpg"),
                name:"运动鞋"
            },
            {
                id:'kong4',
                img:require("../assets/images/nanx4.jpg"),
                name:"一脚蹬"
            },
            {
                id:'kong4',
                img:require("../assets/images/nanx5.jpg"),
                name:"商务鞋"
            },
            {
                id:'kong4',
                img:require("../assets/images/nanx6.jpg"),
                name:"休闲皮鞋"
            },
            {
                id:'kong4',
                img:require("../assets/images/nanx7.jpg"),
                name:"小白鞋"
            },
            {
                id:'kong4',
                img:require("../assets/images/nan'x8.jpg"),
                name:"板鞋"
            },
            {
                id:'kong4',
                img:require("../assets/images/nanx9.png"),
                name:"帆布鞋"
            },
            {
                id:'kong4',
                img:require("../assets/images/kong4.webp"),
                name:"单鞋"
            },
            {
                id:'kong2',
                img:require("../assets/images/kong2.webp"),
                name:"尖头细高跟"
            },
            {
                id:'kong1',
                img:require("../assets/images/kong1.webp"),
                name:"休闲单鞋"
            }
          ]
        },
        {
            name:'手表配饰',
            content:[
                {
                     id:'shis8',
                    img:require("../assets/images/peis1.jpg"),
                    name:"耳环首饰"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis2.jpg"),
                    name:"石英表"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis3.jpg"),
                    name:"太阳眼镜"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis4.jpg"),
                    name:"防晒用品"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis5.jpg"),
                    name:"黄金首饰"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis6.jpg"),
                    name:"机械表"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis7.jpg"),
                    name:"戒指"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis8.jpg"),
                    name:"钻石吊坠"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis9.jpg"),
                    name:"k金项链"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/pei10.jpg"),
                    name:"k金戒指"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis11.jpg"),
                    name:"铂金戒指"
                },
                 {
                     id:'shis8',
                    img:require("../assets/images/peis2.jpg"),
                    name:"石英表"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis3.jpg"),
                    name:"太阳眼镜"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis4.jpg"),
                    name:"防晒用品"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis5.jpg"),
                    name:"黄金首饰"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis6.jpg"),
                    name:"机械表"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis7.jpg"),
                    name:"戒指"
                },
                {
                     id:'shis8',
                    img:require("../assets/images/peis8.jpg"),
                    name:"钻石吊坠"
                }
            ]
        },
        {
            name:'护肤彩妆',
            content:[
                {
                    id:'beauty2',
                    img:require("../assets/images/huf1.png"),
                    name:'面膜'
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf2.jpg"),
                    name:"护肤套装"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf3.jpg"),
                    name:"面部精华"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf4.png"),
                    name:"卸妆"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf5.jpg"),
                    name:"洁面"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf6.png"),
                    name:"化妆水"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf7.jpg"),
                    name:"眼部护理"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf8.jpg"),
                    name:"面霜"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf9.jpg"),
                    name:"防晒"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf10.png"),
                    name:"乳液"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf11.png"),
                    name:"唇部护理"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf12.jpg"),
                    name:"T区护理"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf13.jpg"),
                    name:"面部喷雾"
                },
                {
                    id:'beauty2',
                    img:require("../assets/images/huf14.png"),
                    name:"啫喱"
                },
                {
                    id:'beauty1',
                    img:require("../assets/images/beauty1.webp"),
                    name:"花肌粹"
                },
                {
                    id:'beauty3',
                    img:require("../assets/images/beauty3.webp"),
                    name:"兰蔻极光水"
                },
                {
                    id:'beauty4',
                    img:require("../assets/images/beauty4webp.webp"),
                    name:"复颜洁面"
                },
                {
                    id:'beauty5',
                    img:require("../assets/images/beauty5.webp"),
                    name:"补水保湿"
                },
                {
                    id:'beauty6',
                    img:require("../assets/images/beauty6.webp"),
                    name:"匀净亮白保湿"
                },
                {
                    id:'beauty7',
                    img:require("../assets/images/beauty7.webp"),
                    name:"A.H.C|烟酰胺"
                }
            ]
        },
        {
            name:'箱包皮包',
            content:[
                {
                    id:'nvy1',
                    img:require("../assets/images/bao1.jpg"),
                    name:'斜挎包'
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao2.jpg"),
                    name:"手提包"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao3.jpg"),
                    name:"双肩包"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao4.jpg"),
                    name:"男包"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao5.jpg"),
                    name:"男/女钱包"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao6.png"),
                    name:"真皮包"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao7.jpg"),
                    name:"拉杆箱"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao8.jpg"),
                    name:"单肩包"
                }
            ]
        },
        {
            name:'户外活动',
            content:[
                {
                    id:'nvy1',
                    img:require("../assets/images/hw1.png"),
                    name:'休闲运动鞋'
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw2.png"),
                    name:"跑步鞋"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw6.png"),
                    name:"防晒衣"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw7.png"),
                    name:"运动套装"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw8.png"),
                    name:"瑜伽服"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw9.png"),
                    name:"夏日泳衣"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw3.png"),
                    name:"凉/拖鞋"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw4.png"),
                    name:"短袖上衣"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw5.png"),
                    name:"运动鞋"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw6.png"),
                    name:"防晒衣"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw7.png"),
                    name:"运动套装"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw8.png"),
                    name:"瑜伽服"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/hw9.png"),
                    name:"夏日泳衣"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao3.jpg"),
                    name:"双肩包"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao4.jpg"),
                    name:"男包"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao5.jpg"),
                    name:"男/女钱包"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao6.png"),
                    name:"真皮包"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao7.jpg"),
                    name:"拉杆箱"
                },
                {
                    id:'nvy1',
                    img:require("../assets/images/bao8.jpg"),
                    name:"单肩包"
                }
            ]
        }
      ]
    };
  },
  methods: {},
  components: {
    bscroll
  },
  created() {
    this.$store.state.showTop = false;
    this.$store.state.showBottom = false;
  }
};
</script>

<style lang="scss" scoped>
</style>