<template>
    <div>
        <clothing 
        :imglist="imglist"
        :select="select"
        :navlist="navlist"
        :goods="goods"
        :color="color"
        ></clothing>
    </div>
</template>

<script>
    import clothing from "../public/clothing.vue"
    export default {
        data(){
            return {
                imglist:[
                    {
                        img:require("../../assets/images/innerwear_bg.webp")
                    },
                    {
                        img:require("../../assets/images/innerwear_lx1.webp")
                    },
                    {
                        img:require("../../assets/images/innwewear_lx2.webp")
                    }
                ],
                select:["精选好货","暖心针织","居家服","保暖打底"],
                navlist:[
                    {
                        img:require("../../assets/images/innerwear_nav1.webp"),
                        name:'精致文胸'
                    },
                    {
                        img:require("../../assets/images/innerwear_nav2.webp"),
                        name:'女家居服'
                    },
                    {
                        img:require("../../assets/images/innerwear_nav3.webp"),
                        name:'女士内裤'
                    },
                    {
                        img:require("../../assets/images/innerwear_nav4.webp"),
                        name:'纯棉睡衣'
                    },
                    {
                        img:require("../../assets/images/innerwear_nav5.webp"),
                        name:'男士内裤'
                    },
                    {
                        img:require("../../assets/images/innerwear_nav6.webp"),
                        name:'睡裙睡袍'
                    },
                    {
                        img:require("../../assets/images/innerwear_nav7.webp"),
                        name:'男家居服'
                    },
                    {
                        img:require("../../assets/images/innerwear_nav8.webp"),
                        name:'运动内衣'
                    }
                ],
                goods:[
                    {
                        id:'inner1',
                        img:require("../../assets/images/innerwear_list1.webp"),
                        name:'美斯',
                        newPrice:'59',
                        oldPrice:180,
                        zk:3.4
                    },
                    {
                        id:'inner2',
                        img:require("../../assets/images/innerwear_list2.webp"),
                        name:'爱慕',
                        newPrice:'99',
                        oldPrice:284,
                        zk:3.1
                    },
                    {
                        id:'inner3',
                        img:require("../../assets/images/innerwear_list3.webp"),
                        name:'美婷',
                        newPrice:'89',
                        oldPrice:199,
                        zk:6.8
                    },
                    {
                        id:'inner4',
                        img:require("../../assets/images/innerwear_list4.webp"),
                        name:'七匹狼',
                        newPrice:'59',
                        oldPrice:79,
                        zk:8.0
                    },
                    {
                        id:'inner5',
                        img:require("../../assets/images/innerwear_list5.webp"),
                        name:'金利来',
                        newPrice:'49',
                        oldPrice:68,
                        zk:7.5
                    },
                    {
                        id:'inner6',
                        img:require("../../assets/images/innerwear_list6.webp"),
                        name:'伊丝艾拉',
                        newPrice:'79',
                        oldPrice:119,
                        zk:5.7
                    },
                    {
                        id:'inner7',
                        img:require("../../assets/images/innerwear_list7.webp"),
                        name:'美思',
                        newPrice:'99',
                        oldPrice:284,
                        zk:2.3
                    },
                    {
                        id:'inner8',
                        img:require("../../assets/images/innerwear_list8.webp"),
                        name:'猫人',
                        newPrice:'55',
                        oldPrice:149,
                        zk:1.9
                    },
                    {
                        id:'inner9',
                        img:require("../../assets/images/innerwear_list9.webp"),
                        name:'木林森',
                        newPrice:'89',
                        oldPrice:478,
                        zk:1.6
                    },
                    {
                        id:'inner10',
                        img:require("../../assets/images/innerwear_list10.webp"),
                        name:'猫人',
                        newPrice:'69',
                        oldPrice:478,
                        zk:0.9
                    },
                    {
                        id:'inner11',
                        img:require("../../assets/images/innerwear_list11.webp"),
                        name:'美思',
                        newPrice:'99',
                        oldPrice:226,
                        zk:3.5
                    },
                    {
                        id:'inner12',
                        img:require("../../assets/images/innerwear_list12.webp"),
                        name:'多拉美',
                        newPrice:'119',
                        oldPrice:689,
                        zk:1.1
                    }
                ],
                color:'rgb(255,226,199)'
            }
        },
        components:{
            clothing
        },
        created() {
            this.$store.state.showTop = false;
            this.$store.state.showBottom = false;
        }
    }
</script>

<style lang="scss" scoped>
   
</style>