export default [
    {
        path:'/my',
        name:'个人中心',
        component:()=>import("../../views/my.vue")
    },
    {
        path:'/login',
        name:'登录',
        component:()=>import("../../components/my/login.vue")
    },
    {
        path:'/register',
        name:'注册',
        component:()=>import("../../components/my/register.vue")
    },
    {
        path:'/money',
        name:'桃依币',
        component:()=>import("../../components/my/money.vue")
    },
    {
        path:'/like',
        name:'我的收藏',
        component:()=>import("../../components/my/like.vue")
    },
    {
        path:'/coupon',
        name:'优惠券',
        component:()=>import("../../components/my/coupon.vue")
    },
    {
        path:'/serve',
        name:'客服',
        component:()=>import("../../components/my/serve.vue")
    },
    {
        path:'/setting',
        name:'账户设置',
        component:()=>import("../../components/my/setting.vue")
    },
    {
        path:'/message',
        name:'消息中心',
        component:()=>import("../../components/my/message.vue")
    },
    {
        path:'/footprint',
        name:'消息中心',
        component:()=>import("../../components/my/footprint.vue")
    }
]